pandas

In [70]:
print("hello")

hello

In [71]:
print("world")

world

In [72]:
import pandas as pd

In [73]:
user = {                           
    "name" : ["Maham","Aleena"], 
    "age" : [21,22],
}
print(user.get("name"))

['Maham', 'Aleena']

In [74]:
df = pd.DataFrame(user) #Convert the dictionary into a table
print(df)

     name  age
0   Maham   21
1  Aleena   22

In [75]:
df["name"] #Use the DataFrame name followed by the column name in square brackets to display name only

0     Maham
1    Aleena
Name: name, dtype: str

In [76]:
df["age"]   #df[["age","name"]] #use 2 square brackets if you want to retrieve more than one coloumn using indexing

0    21
1    22
Name: age, dtype: int64

In [77]:
df["age"].mean() #Pandas has a built-in method for calculating an average.

np.float64(21.5)

In [78]:
df[df['age'] > 21] #Use a comparison operator inside the DataFrame column selection.

     name  age
1  Aleena   22

In [79]:
df["city"] = ["Karachi", "Lahore"] #Add a new column of city.
print(df)

     name  age     city
0   Maham   21  Karachi
1  Aleena   22   Lahore

In [80]:
import pandas as pd

data = {
    "name": ["Maham", "Aleena", "Sara", "Ayesha", "Hina"],
    "age": [21, 22, 19, 24, 20],
    "marks": [85, 92, 78, 95, 88]
}

df = pd.DataFrame(data)  #dict to table

print(df)
print("Average marks:", df["marks"].mean())  #average of marks coloumn
print("Highest marks:", df["marks"].max())   #max marks in the mark coloumn
print("Lowest marks:", df["marks"].min())    #min marks in the mark coloumn

print("\nStudents scoring above 85:")
print(df[df["marks"] > 85]) #condition

     name  age  marks
0   Maham   21     85
1  Aleena   22     92
2    Sara   19     78
3  Ayesha   24     95
4    Hina   20     88
Average marks: 87.6
Highest marks: 95
Lowest marks: 78

Students scoring above 85:
     name  age  marks
1  Aleena   22     92
3  Ayesha   24     95
4    Hina   20     88

In [81]:

import pandas as pd

# Sample student data to explore
data = {
    "name": ["Maham", "Aleena", "Sara", "Ayesha", "Hina"],
    "age": [21, 22, 19, 24, 20],
    "marks": [85, 92, 78, 95, 88]
}

df = pd.DataFrame(data)

# Check how many rows and columns the DataFrame contains
print("Dataset dimensions:", df.shape)

# Display all column names
print("\nColumn names:")
print(df.columns)

# Check the data type of each column
print("\nColumn data types:")
print(df.dtypes)

# Display a summary of the DataFrame
# use whenever you load a new CSV or Excel dataset and want to check its columns, data types, missing values, and overall structure
print("\nDataset information:")   
df.info()   

# Get statistical information about numerical columns
print("\nStatistical summary:")
print(df.describe())
# df.describe(include="all") to include text coloumns

# Display the first and last five rows (by default)
print("\nFirst five rows:")    
print(df.head())
# print(df.head(2)) display first 2 rows

print("\nLast five rows:")     
print(df.tail())
# print(df.tail(2)) display last 2 rows

Dataset dimensions: (5, 3)

Column names:
Index(['name', 'age', 'marks'], dtype='str')

Column data types:
name       str
age      int64
marks    int64
dtype: object

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   age     5 non-null      int64
 2   marks   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

Statistical summary:
             age      marks
count   5.000000   5.000000
mean   21.200000  87.600000
std     1.923538   6.580274
min    19.000000  78.000000
25%    20.000000  85.000000
50%    21.000000  88.000000
75%    22.000000  92.000000
max    24.000000  95.000000

First five rows:
     name  age  marks
0   Maham   21     85
1  Aleena   22     92
2    Sara   19     78
3  Ayesha   24     95
4    Hina   20     88

Last five rows:
     name  age  marks
0   Maham   21     85
1  Aleena   22     92
2    Sara   19     78
3  Ayesha   24     95
4    Hina   20     88

In [82]:
import pandas as pd

data = {
    "name": ["Maham", "Aleena", "Sara", "Ayesha", "Hina"],
    "age": [21, 22, 19, 24, 20],
    "marks": [85, 92, 78, 95, 88]
}

df = pd.DataFrame(data)

# loc means select by index label
# This selects the row whose index label is 0
print(df.loc[0])

#To select a particular value
print(df.loc[0, "name"])

# iloc means select by integer position
# This selects the first row because Python positions start at zero
print(df.iloc[0])

# To retrieve a particular value
print(df.iloc[0, 1])

name     Maham
age         21
marks       85
Name: 0, dtype: object
Maham
name     Maham
age         21
marks       85
Name: 0, dtype: object
21

In [83]:
import pandas as pd
data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Math": [85, 92, 78],
    "Science": [80, 89, 75]
}
df = pd.DataFrame(data)
df

    Name  Math  Science
0    Ali    85       80
1   Sara    92       89
2  Ahmed    78       75

In [84]:
df["Science"]

0    80
1    89
2    75
Name: Science, dtype: int64

In [85]:
df["Math"]

0    85
1    92
2    78
Name: Math, dtype: int64

In [86]:
df["total"] = df["Math"] + df["Science"]  #addition 
df

    Name  Math  Science  total
0    Ali    85       80    165
1   Sara    92       89    181
2  Ahmed    78       75    153

In [87]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Ali", "Sara", "Ahmed", "Hina"],
    "total": [80, 120, 95, 150]
})

In [ ]:
# Checks whether each value in the total column is greater than or equal to 100 and returns true or false
df["total"] >= 100

0    False
1     True
2    False
3     True
Name: total, dtype: bool

In [ ]:
# To keep the rows where the condition is True and excludes rows where it is False, it returns number
df[df["total"] >= 100]

   name  total
1  Sara    120
3  Hina    150

In [ ]:
# calling a csv file that is in project folder
import pandas as pd 

df = pd.read_csv("pandas_employee_dataset.csv")
df

,employee_id,name,department,age,salary_pkr,years_experience,performance_score,city,remote
0,1001,Ayesha Khan,Sales,24.0,65000.0,1.0,3.8,Karachi,No
1,1002,Bilal Ahmed,IT,29.0,95000.0,5.0,4.5,Lahore,Yes
2,1003,Sara Malik,HR,NaN,72000.0,3.0,4.1,Karachi,No
3,1004,Usman Ali,IT,35.0,NaN,8.0,NaN,Islamabad,Yes
4,1005,Hina Shah,Finance,27.0,88000.0,NaN,4.7,Lahore,No
5,1006,Hamza Raza,Sales,31.0,68000.0,4.0,3.6,NaN,NaN
6,1007,Noor Fatima,NaN,26.0,70000.0,2.0,4.0,Karachi,Yes
7,1008,Daniyal Iqbal,Marketing,NaN,81000.0,6.0,4.2,Peshawar,Yes
8,1009,Mariam Tariq,HR,30.0,NaN,7.0,4.4,Islamabad,No
9,1010,Zain Abbas,Finance,42.0,125000.0,15.0,4.8,Karachi,No
10,1011,Laiba Noor,IT,23.0,78000.0,1.0,NaN,Lahore,Yes
11,1012,Omar Siddiqui,Marketing,34.0,90000.0,NaN,4.1,Quetta,Yes

In [91]:
# Checks every cell in the DataFrame and returns:
# - True if the value is missing.
# - False if the value is present.
df.isnull()

,employee_id,name,department,age,salary_pkr,years_experience,performance_score,city,remote
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False
3,False,False,False,False,True,False,True,False,False
4,False,False,False,False,False,True,False,False,False
5,False,False,False,False,False,False,False,True,True
6,False,False,True,False,False,False,False,False,False
7,False,False,False,True,False,False,False,False,False
8,False,False,False,False,True,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,True,False,False
11,False,False,False,False,False,True,False,False,False

In [92]:
# Counts the missing values in each column.
# For example, if the age column has 2 missing values, its result will show age    2.
df.isnull().sum()

employee_id          0
name                 0
department           1
age                  2
salary_pkr           2
years_experience     2
performance_score    2
city                 1
remote               1
dtype: int64

In [93]:
df.isna().sum #isna and isnull are same

<bound method DataFrame.sum of     employee_id   name  department    age  salary_pkr  years_experience  \
0         False  False       False  False       False             False
1         False  False       False  False       False             False
2         False  False       False   True       False             False
3         False  False       False  False        True             False
4         False  False       False  False       False              True
5         False  False       False  False       False             False
6         False  False        True  False       False             False
7         False  False       False   True       False             False
8         False  False       False  False        True             False
9         False  False       False  False       False             False
10        False  False       False  False       False             False
11        False  False       False  False       False              True

    performance_score   city  remote
0               False  False   False
1               False  False   False
2               False  False   False
3                True  False   False
4               False  False   False
5               False   True    True
6               False  False   False
7               False  False   False
8               False  False   False
9               False  False   False
10               True  False   False
11              False  False   False  >

In [94]:
# Removes every row that contains at least one missing value and returns the cleaned DataFrame. 
# It does not permanently modify df unless you assign the result back
df.dropna()

,employee_id,name,department,age,salary_pkr,years_experience,performance_score,city,remote
0,1001,Ayesha Khan,Sales,24.0,65000.0,1.0,3.8,Karachi,No
1,1002,Bilal Ahmed,IT,29.0,95000.0,5.0,4.5,Lahore,Yes
9,1010,Zain Abbas,Finance,42.0,125000.0,15.0,4.8,Karachi,No

In [96]:
df = pd.read_excel("pandas_employee_dataset.xlsx") #calling an excel file that is in project folder
df

,employee_id,name,department,age,salary_pkr,years_experience,performance_score,city,remote
0,1001,Ayesha Khan,Sales,24.0,65000.0,1.0,3.8,Karachi,No
1,1002,Bilal Ahmed,IT,29.0,95000.0,5.0,4.5,Lahore,Yes
2,1003,Sara Malik,HR,NaN,72000.0,3.0,4.1,Karachi,No
3,1004,Usman Ali,IT,35.0,NaN,8.0,NaN,Islamabad,Yes
4,1005,Hina Shah,Finance,27.0,88000.0,NaN,4.7,Lahore,No
5,1006,Hamza Raza,Sales,31.0,68000.0,4.0,3.6,NaN,NaN
6,1007,Noor Fatima,NaN,26.0,70000.0,2.0,4.0,Karachi,Yes
7,1008,Daniyal Iqbal,Marketing,NaN,81000.0,6.0,4.2,Peshawar,Yes
8,1009,Mariam Tariq,HR,30.0,NaN,7.0,4.4,Islamabad,No
9,1010,Zain Abbas,Finance,42.0,125000.0,15.0,4.8,Karachi,No
10,1011,Laiba Noor,IT,23.0,78000.0,1.0,NaN,Lahore,Yes
11,1012,Omar Siddiqui,Marketing,34.0,90000.0,NaN,4.1,Quetta,Yes