pandas

In [91]:
print("hello")

hello

In [92]:
print("world")

world

In [93]:
import pandas as pd

DataFrame

In [94]:
# DataFrame using Dictionary
user = {                           
    "name" : ["Maham","Aleena"], 
    "age" : [21,22],
}
print(user.get("name"))

['Maham', 'Aleena']

In [95]:
df = pd.DataFrame(user) #Convert the dictionary into a table
print(df)

     name  age
0   Maham   21
1  Aleena   22

In [96]:
df["name"] #Use the DataFrame name followed by the column name in square brackets to display name only

0     Maham
1    Aleena
Name: name, dtype: str

In [97]:
df["age"]   #df[["age","name"]] #use 2 square brackets if you want to retrieve more than one coloumn using indexing

0    21
1    22
Name: age, dtype: int64

In [98]:
df["age"].mean() #Pandas has a built-in method for calculating an average.

np.float64(21.5)

In [99]:
df[df['age'] > 21] #Use a comparison operator inside the DataFrame column selection.

     name  age
1  Aleena   22

In [100]:
df["city"] = ["Karachi", "Lahore"] #Add a new column of city.
print(df)

     name  age     city
0   Maham   21  Karachi
1  Aleena   22   Lahore

In [101]:
# DataFrame from list of lists
data = [["Ali", 22], ["Sara", 25], ["Ahmed", 30]]
df = pd.DataFrame(data, columns=["Name", "Age"])
print(df)

    Name  Age
0    Ali   22
1   Sara   25
2  Ahmed   30

In [102]:
# DataFrame from list of dictionaries
data = [
    {"Product": "Laptop", "Price": 80000},
    {"Product": "Mouse", "Price": 1500},
]
df = pd.DataFrame(data)
print(df)

  Product  Price
0  Laptop  80000
1   Mouse   1500

In [103]:
print(df.shape)       # (rows, columns) -> (4, 3)
print(df.columns)     # column names
print(df.index)       # row index
print(df.dtypes)      # data type of each column
print(df.info())      # summary of DataFrame
print(df.head(2))     # first 2 rows
print(df.tail(2))     # last 2 rows
print(df.describe())  # statistical summary (numeric columns)

(2, 2)
Index(['Product', 'Price'], dtype='str')
RangeIndex(start=0, stop=2, step=1)
Product      str
Price      int64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Product  2 non-null      str
 1   Price    2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes
None
  Product  Price
0  Laptop  80000
1   Mouse   1500
  Product  Price
0  Laptop  80000
1   Mouse   1500
              Price
count      2.000000
mean   40750.000000
std    55507.882323
min     1500.000000
25%    21125.000000
50%    40750.000000
75%    60375.000000
max    80000.000000

In [104]:
import pandas as pd

data = {
    "name": ["Maham", "Aleena", "Sara", "Ayesha", "Hina"],
    "age": [21, 22, 19, 24, 20],
    "marks": [85, 92, 78, 95, 88]
}

df = pd.DataFrame(data)  #dict to table

print(df)
print("Average marks:", df["marks"].mean())  #average of marks coloumn
print("Highest marks:", df["marks"].max())   #max marks in the mark coloumn
print("Lowest marks:", df["marks"].min())    #min marks in the mark coloumn

print("\nStudents scoring above 85:")
print(df[df["marks"] > 85]) #condition

     name  age  marks
0   Maham   21     85
1  Aleena   22     92
2    Sara   19     78
3  Ayesha   24     95
4    Hina   20     88
Average marks: 87.6
Highest marks: 95
Lowest marks: 78

Students scoring above 85:
     name  age  marks
1  Aleena   22     92
3  Ayesha   24     95
4    Hina   20     88

In [105]:

import pandas as pd

# Sample student data to explore
data = {
    "name": ["Maham", "Aleena", "Sara", "Ayesha", "Hina"],
    "age": [21, 22, 19, 24, 20],
    "marks": [85, 92, 78, 95, 88]
}

df = pd.DataFrame(data)

# Check how many rows and columns the DataFrame contains
print("Dataset dimensions:", df.shape)

# Display all column names
print("\nColumn names:")
print(df.columns)

# Check the data type of each column
print("\nColumn data types:")
print(df.dtypes)

# Display a summary of the DataFrame
# use whenever you load a new CSV or Excel dataset and want to check its columns, data types, missing values, and overall structure
print("\nDataset information:")   
df.info()   

# Get statistical information about numerical columns
print("\nStatistical summary:")
print(df.describe())
# df.describe(include="all") to include text coloumns

# Display the first and last five rows (by default)
print("\nFirst five rows:")    
print(df.head())
# print(df.head(2)) display first 2 rows

print("\nLast five rows:")     
print(df.tail())
# print(df.tail(2)) display last 2 rows

Dataset dimensions: (5, 3)

Column names:
Index(['name', 'age', 'marks'], dtype='str')

Column data types:
name       str
age      int64
marks    int64
dtype: object

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   age     5 non-null      int64
 2   marks   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

Statistical summary:
             age      marks
count   5.000000   5.000000
mean   21.200000  87.600000
std     1.923538   6.580274
min    19.000000  78.000000
25%    20.000000  85.000000
50%    21.000000  88.000000
75%    22.000000  92.000000
max    24.000000  95.000000

First five rows:
     name  age  marks
0   Maham   21     85
1  Aleena   22     92
2    Sara   19     78
3  Ayesha   24     95
4    Hina   20     88

Last five rows:
     name  age  marks
0   Maham   21     85
1  Aleena   22     92
2    Sara   19     78
3  Ayesha   24     95
4    Hina   20     88

In [106]:
# MINI PROJECT #1 — Student Result Card System
# Task: Ek DataFrame banayein jis mein 6 students ka Name, Roll No, Math, Science, English marks hon.
# DataFrame print karein.
# .describe() se average marks nikaalein.
# .shape se total students aur columns count karein.
# Sab se zyada marks lene wale student ka naam nikaalein (hint: .loc[df['Math'].idxmax()]).

import pandas as pd

data = {
    "Name": ["Ali", "Sara", "Ahmed", "Zara", "Bilal", "Hina"],
    "RollNo": [1, 2, 3, 4, 5, 6],
    "Math": [85, 92, 78, 88, 95, 70],
    "Science": [80, 89, 75, 90, 91, 65],
    "English": [88, 94, 80, 85, 89, 72]
}
df = pd.DataFrame(data)
print(df)
print(df.describe())
print("Top Math Scorer:", df.loc[df['Math'].idxmax(), 'Name'])

    Name  RollNo  Math  Science  English
0    Ali       1    85       80       88
1   Sara       2    92       89       94
2  Ahmed       3    78       75       80
3   Zara       4    88       90       85
4  Bilal       5    95       91       89
5   Hina       6    70       65       72
         RollNo       Math    Science    English
count  6.000000   6.000000   6.000000   6.000000
mean   3.500000  84.666667  81.666667  84.666667
std    1.870829   9.287985  10.347302   7.737355
min    1.000000  70.000000  65.000000  72.000000
25%    2.250000  79.750000  76.250000  81.250000
50%    3.500000  86.500000  84.500000  86.500000
75%    4.750000  91.000000  89.750000  88.750000
max    6.000000  95.000000  91.000000  94.000000
Top Math Scorer: Bilal

In [107]:
import pandas as pd

data = {
    "name": ["Maham", "Aleena", "Sara", "Ayesha", "Hina"],
    "age": [21, 22, 19, 24, 20],
    "marks": [85, 92, 78, 95, 88]
}

df = pd.DataFrame(data)

# loc means select by index label
# This selects the row whose index label is 0
print(df.loc[0])

#To select a particular value
print(df.loc[0, "name"])

# iloc means select by integer position
# This selects the first row because Python positions start at zero
print(df.iloc[0])

# To retrieve a particular value
print(df.iloc[0, 1])

name     Maham
age         21
marks       85
Name: 0, dtype: object
Maham
name     Maham
age         21
marks       85
Name: 0, dtype: object
21

In [108]:
import pandas as pd
data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Math": [85, 92, 78],
    "Science": [80, 89, 75]
}
df = pd.DataFrame(data)
df

    Name  Math  Science
0    Ali    85       80
1   Sara    92       89
2  Ahmed    78       75

In [109]:
df["Science"]

0    80
1    89
2    75
Name: Science, dtype: int64

In [110]:
df["Math"]

0    85
1    92
2    78
Name: Math, dtype: int64

In [111]:
df["total"] = df["Math"] + df["Science"]  #addition 
df

    Name  Math  Science  total
0    Ali    85       80    165
1   Sara    92       89    181
2  Ahmed    78       75    153

In [112]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Ali", "Sara", "Ahmed", "Hina"],
    "total": [80, 120, 95, 150]
})

In [113]:
# Checks whether each value in the total column is greater than or equal to 100 and returns true or false
df["total"] >= 100

0    False
1     True
2    False
3     True
Name: total, dtype: bool

In [114]:
# To keep the rows where the condition is True and excludes rows where it is False, it returns number
df[df["total"] >= 100]

   name  total
1  Sara    120
3  Hina    150

READING DATA (CSV, Excel, JSON, SQL)

In [115]:
# calling a csv file that is in project folder
import pandas as pd 

df = pd.read_csv("pandas_employee_dataset.csv")
df

,employee_id,name,department,age,salary_pkr,years_experience,performance_score,city,remote
0,1001,Ayesha Khan,Sales,24.0,65000.0,1.0,3.8,Karachi,No
1,1002,Bilal Ahmed,IT,29.0,95000.0,5.0,4.5,Lahore,Yes
2,1003,Sara Malik,HR,NaN,72000.0,3.0,4.1,Karachi,No
3,1004,Usman Ali,IT,35.0,NaN,8.0,NaN,Islamabad,Yes
4,1005,Hina Shah,Finance,27.0,88000.0,NaN,4.7,Lahore,No
5,1006,Hamza Raza,Sales,31.0,68000.0,4.0,3.6,NaN,NaN
6,1007,Noor Fatima,NaN,26.0,70000.0,2.0,4.0,Karachi,Yes
7,1008,Daniyal Iqbal,Marketing,NaN,81000.0,6.0,4.2,Peshawar,Yes
8,1009,Mariam Tariq,HR,30.0,NaN,7.0,4.4,Islamabad,No
9,1010,Zain Abbas,Finance,42.0,125000.0,15.0,4.8,Karachi,No
10,1011,Laiba Noor,IT,23.0,78000.0,1.0,NaN,Lahore,Yes
11,1012,Omar Siddiqui,Marketing,34.0,90000.0,NaN,4.1,Quetta,Yes

In [116]:
# Checks every cell in the DataFrame and returns:
# - True if the value is missing.
# - False if the value is present.
df.isnull()

,employee_id,name,department,age,salary_pkr,years_experience,performance_score,city,remote
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False
3,False,False,False,False,True,False,True,False,False
4,False,False,False,False,False,True,False,False,False
5,False,False,False,False,False,False,False,True,True
6,False,False,True,False,False,False,False,False,False
7,False,False,False,True,False,False,False,False,False
8,False,False,False,False,True,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,True,False,False
11,False,False,False,False,False,True,False,False,False

In [117]:
# Counts the missing values in each column.
# For example, if the age column has 2 missing values, its result will show age    2.
df.isnull().sum()

employee_id          0
name                 0
department           1
age                  2
salary_pkr           2
years_experience     2
performance_score    2
city                 1
remote               1
dtype: int64

In [118]:
df.isna().sum #isna and isnull are same

<bound method DataFrame.sum of     employee_id   name  department    age  salary_pkr  years_experience  \
0         False  False       False  False       False             False
1         False  False       False  False       False             False
2         False  False       False   True       False             False
3         False  False       False  False        True             False
4         False  False       False  False       False              True
5         False  False       False  False       False             False
6         False  False        True  False       False             False
7         False  False       False   True       False             False
8         False  False       False  False        True             False
9         False  False       False  False       False             False
10        False  False       False  False       False             False
11        False  False       False  False       False              True

    performance_score   city  remote
0               False  False   False
1               False  False   False
2               False  False   False
3                True  False   False
4               False  False   False
5               False   True    True
6               False  False   False
7               False  False   False
8               False  False   False
9               False  False   False
10               True  False   False
11              False  False   False  >

In [119]:
# Removes every row that contains at least one missing value and returns the cleaned DataFrame. 
# It does not permanently modify df unless you assign the result back
df.dropna()

,employee_id,name,department,age,salary_pkr,years_experience,performance_score,city,remote
0,1001,Ayesha Khan,Sales,24.0,65000.0,1.0,3.8,Karachi,No
1,1002,Bilal Ahmed,IT,29.0,95000.0,5.0,4.5,Lahore,Yes
9,1010,Zain Abbas,Finance,42.0,125000.0,15.0,4.8,Karachi,No

In [120]:
df = pd.read_excel("pandas_employee_dataset.xlsx") #calling an excel file that is in project folder
df

,employee_id,name,department,age,salary_pkr,years_experience,performance_score,city,remote
0,1001,Ayesha Khan,Sales,24.0,65000.0,1.0,3.8,Karachi,No
1,1002,Bilal Ahmed,IT,29.0,95000.0,5.0,4.5,Lahore,Yes
2,1003,Sara Malik,HR,NaN,72000.0,3.0,4.1,Karachi,No
3,1004,Usman Ali,IT,35.0,NaN,8.0,NaN,Islamabad,Yes
4,1005,Hina Shah,Finance,27.0,88000.0,NaN,4.7,Lahore,No
5,1006,Hamza Raza,Sales,31.0,68000.0,4.0,3.6,NaN,NaN
6,1007,Noor Fatima,NaN,26.0,70000.0,2.0,4.0,Karachi,Yes
7,1008,Daniyal Iqbal,Marketing,NaN,81000.0,6.0,4.2,Peshawar,Yes
8,1009,Mariam Tariq,HR,30.0,NaN,7.0,4.4,Islamabad,No
9,1010,Zain Abbas,Finance,42.0,125000.0,15.0,4.8,Karachi,No
10,1011,Laiba Noor,IT,23.0,78000.0,1.0,NaN,Lahore,Yes
11,1012,Omar Siddiqui,Marketing,34.0,90000.0,NaN,4.1,Quetta,Yes

SERIES

In [121]:
# Simple Series from a list
import pandas as pd

ages = pd.Series([25, 30, 22, 40])
print(ages)

0    25
1    30
2    22
3    40
dtype: int64

In [122]:
# Series with custom index
                    #values                 #label
marks = pd.Series([85, 90, 78], index=["Ali", "Sara", "Ahmed"])
print(marks)

Ali      85
Sara     90
Ahmed    78
dtype: int64

In [123]:
# Series from a dictionary
population = pd.Series({"Karachi": 16000000, "Lahore": 11000000, "Islamabad": 1200000})
print(population)

Karachi      16000000
Lahore       11000000
Islamabad     1200000
dtype: int64

In [124]:
# Accessing Series Data
marks = pd.Series([85, 90, 78], index=["Ali", "Sara", "Ahmed"])
#print(marks)
print(marks["Ali"])      # Value by label -> 85
#print(marks[0])          # Value by position -> 85 (older pandas) / use marks.iloc[0]
print(marks.values)      # array([85, 90, 78])
print(marks.index)       # Index(['Ali', 'Sara', 'Ahmed'])

85
[85 90 78]
Index(['Ali', 'Sara', 'Ahmed'], dtype='str')